backend/controllers/ReviewController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Review;
use backend\models\SearchReview;
use backend\models\SearchComment;
use backend\models\Comment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\rbac\DbManager;


use yii\web\UploadedFile;


/**
 * ReviewController implements the CRUD actions for Review model.
 */
class ReviewController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Review models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchReview();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Review model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Review model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if( Yii::$app->user->can('create-post'))
        {
            $model = new Review();


            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->id_author = Yii::$app->user->identity->id;
                $model->id_category = 1;
                $model->createon = date('Y-m-d h:m:s');

                $model->file = UploadedFile::getInstance($model, 'file');
                $save_file = '';
                if(isset($model->file)){
                    $imageid = $model->idpost;
                    $imagepath = 'uploadsimage/'; // Create folder under web/uploads/logo
                    $model->img = $imagepath .$imageid.'-'.$model->file->name;
                    $save_file = 1;
                }
        
                if ($model->save()) {
                        if($save_file){
                            $model->file->saveAs($model->img);
                            return $this->redirect(['details', 'id' => $model->idpost]);
                        }
                        else{
                            return $this->redirect(['details', 'id' => $model->idpost]);                            
                        }
                }else{
                    return $this->redirect(['details', 'id' => $model->idpost]);
                }
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }   
        else
        {
            throw new ForbiddenHttpException;
            
        }
    }

    /**
     * Updates an existing Review model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {


                $model->id_author = Yii::$app->user->identity->id;
                $model->createon = date('Y-m-d h:m:s');
                $model->id_category = 1;

                $model->file = UploadedFile::getInstance($model, 'file');
                $save_file = '';
                if($model->file){
                    $imageid = $model->idpost;
                    $imagepath = 'uploadsimage/'; // Create folder under web/uploads/logo
                    $model->img = $imagepath .$imageid.'-'.$model->file->name;
                    $save_file = 1;
                }
        
                if ($model->save()) {
                        if($save_file){
                            $model->file->saveAs($model->img);
                            return $this->redirect(['details', 'id' => $model->idpost]);
                        }
                }else{
                    return $this->redirect(['details', 'id' => $model->idpost]);
                }

                return $this->redirect(['details', 'id' => $model->idpost]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


    public function actionDetails($id)
    {
        $searchModel = new SearchReview();
        $sidebarProvider = $searchModel->sidebarsearch(Yii::$app->request->queryParams);

        $searchModelComment = new SearchComment();
        $dataProvider = $searchModelComment->searchforeview($id);
        //print_r($dataProvider);
        //die();



        //add model for create comment
        $modelcomment = new Comment();

        if ($modelcomment->load(Yii::$app->request->post()) && $modelcomment->save()) {
            $done = 1;
            return $this->render('detail', [
                'model' => $this->findModel($id),
                'sidebarProvider' => $sidebarProvider,
                'searchModelComment' => $searchModelComment,
                'dataProvider' => $dataProvider,
                'modelcomment' => $modelcomment,
                'done' => $done,
            ]);
        } else {
        return $this->render('detail', [
            'model' => $this->findModel($id),
            'sidebarProvider' => $sidebarProvider,
            'searchModelComment' => $searchModelComment,
            'dataProvider' => $dataProvider,
            'modelcomment' => $modelcomment,
        ]);
        }

    }

    /**
     * Deletes an existing Review model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Review model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Review the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Review::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use app\models\Review;
use backend\models\SearchReview;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new SearchReview();
        $dataProvider = $searchModel->indexsearch(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        //return $this->goHome();
        return $this->redirect(substr_replace(Yii::$app->urlManagerFrontEnd->createUrl(''),"", -1));
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\AuthItems;
use backend\models\SearchReview;

use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchReview();
        $dataProvider = $searchModel->indexsearch(Yii::$app->request->queryParams);
        $backendlink = Yii::$app->urlManagerBackEnd->createUrl('');
        //print_r($backendlink);
        //die();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'backendlink' => $backendlink,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            //return $this->goBack();
            return $this->redirect('../../../../backend/web/index.php/');
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        $authItems = AuthItems::find()->where(['not like', 'name', 'Admin'])->all();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect('../../../../backend/web/index.php/');
                    //return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
            'authItems' => $authItems,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error"><br/><br/>

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\web\View;
//use yii\grid\ListView;
/* @var $this yii\web\View */

$this->title = 'My Yii Application';
$jsView = file_get_contents(Yii::getAlias('@webroot/css/slider/unslidershown.js'));
$this->registerJs($jsView, View::POS_END);

?>


    </div>
    <header>
        <div class="header-content">
            <div class="header-content-inner" style="text-align:left">
                <div class="row">
                    <div class="col-lg-4 col-sm-12">
                        <h1>Hello,<br/><?= Yii::$app->user->identity->firstname." ".Yii::$app->user->identity->lastname ?></h1>
                        <br/>
                         <?= Html::a('New Review', ['/review/create'], ['class' => 'btn btn-primary btn-xl page-scrol']) ?>
                    </div>
                    <div class="col-lg-8 col-sm-12">
                        <span>Latest Review by You :</span>
                        <div class="my-slider">
                            <ul>
                            <?php  
                                $showone = 1;
                                foreach ($dataProvider->models as $model) { 
                                    if($model->id_author==Yii::$app->user->identity->id){ 
                                        echo "<li class='text-center'><a href='review/details?id={$model->idpost}'>";
                                        if($model->img==''){
                                            echo "<img src='../img/noimages.jpg' class='img-responsive' alt='' style='width:100%'>";
                                        }
                                        else{
                                            echo "<img src='../{$model->img}' class='img-responsive' alt='' style='width:100%;max-height:350px'>";                        
                                        }
                                        echo "<div class='' style='background: rgba(0, 0, 0, .5);width:100%;font-family:Helvetica;text-decoration:none'>{$model->subject}</div></a></li>";
                                    }
                                    else{
                                        if($showone==1){
                                            echo "<li class='text-center'><a href='review/create'>";
                                            echo "<img src='../img/noreview.jpg' class='img-responsive' alt='' style='width:100%'>";
                                            echo "</a></li>";
                                        }
                                    }
                                $showone++;
                                }
                            ?>
                            </ul>
                        </div>
                    </div>
                </div> 

            </div>
        </div>
    </header>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">

            <?php  
                foreach ($dataProvider->models as $model) {     
                    echo "<div class='col-lg-4 col-sm-6'><a href='review/details?id={$model->idpost}' class='portfolio-box'>";
                    if($model->img==''){
                        echo "<img src='../img/noimages.jpg' class='img-responsive' alt='' style='height:222px;width:100%'>";
                    }
                    else{
                        echo "<img src='../{$model->img}' class='img-responsive' alt='' style='height:222px;width:100%'>";                        
                    }
                    echo "<div class='portfolio-box-caption'>
                                    <div class='portfolio-box-caption-content'>
                                        <div class='project-category text-faded'>
                                            {$model->subject}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>";
                } 
            ?>
            </div>
        </div>
    </section>


    <style type="text/css">
    .navbar-inverse{background: transparent;
    border:0;}
    </style>

   

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>