backend/controllers/CommentController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Comment;
use backend\models\SearchComment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchComment();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comment model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idcomment]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idcomment]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/ReviewController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Review;
use backend\models\SearchReview;
use backend\models\SearchComment;
use backend\models\Comment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\rbac\DbManager;


use yii\web\UploadedFile;


/**
 * ReviewController implements the CRUD actions for Review model.
 */
class ReviewController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Review models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchReview();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Review model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Review model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if( Yii::$app->user->can('create-post'))
        {
            $model = new Review();


            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->id_author = Yii::$app->user->identity->id;
                $model->id_category = 1;
                $model->createon = date('Y-m-d h:m:s');

                $model->file = UploadedFile::getInstance($model, 'file');
                $save_file = '';
                if(isset($model->file)){
                    $imageid = $model->idpost;
                    $imagepath = 'uploadsimage/'; // Create folder under web/uploads/logo
                    $model->img = $imagepath .$imageid.'-'.$model->file->name;
                    $save_file = 1;
                }
        
                if ($model->save()) {
                        if($save_file){
                            $model->file->saveAs($model->img);
                            return $this->redirect(['details', 'id' => $model->idpost]);
                        }
                        else{
                            return $this->redirect(['details', 'id' => $model->idpost]);                            
                        }
                }else{
                    return $this->redirect(['details', 'id' => $model->idpost]);
                }
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }   
        else
        {
            throw new ForbiddenHttpException;
            
        }
    }

    /**
     * Updates an existing Review model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {


                $model->id_author = Yii::$app->user->identity->id;
                $model->createon = date('Y-m-d h:m:s');
                $model->id_category = 1;

                $model->file = UploadedFile::getInstance($model, 'file');
                $save_file = '';
                if($model->file){
                    $imageid = $model->idpost;
                    $imagepath = 'uploadsimage/'; // Create folder under web/uploads/logo
                    $model->img = $imagepath .$imageid.'-'.$model->file->name;
                    $save_file = 1;
                }
        
                if ($model->save()) {
                        if($save_file){
                            $model->file->saveAs($model->img);
                            return $this->redirect(['details', 'id' => $model->idpost]);
                        }
                }else{
                    return $this->redirect(['details', 'id' => $model->idpost]);
                }

                return $this->redirect(['details', 'id' => $model->idpost]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }


    public function actionDetails($id)
    {
        $searchModel = new SearchReview();
        $sidebarProvider = $searchModel->sidebarsearch(Yii::$app->request->queryParams);

        $searchModelComment = new SearchComment();
        $dataProvider = $searchModelComment->searchforeview($id);
        //print_r($dataProvider);
        //die();



        //add model for create comment
        $modelcomment = new Comment();

        if ($modelcomment->load(Yii::$app->request->post()) && $modelcomment->save()) {
            $done = 1;
            return $this->render('detail', [
                'model' => $this->findModel($id),
                'sidebarProvider' => $sidebarProvider,
                'searchModelComment' => $searchModelComment,
                'dataProvider' => $dataProvider,
                'modelcomment' => $modelcomment,
                'done' => $done,
            ]);
        } else {
        return $this->render('detail', [
            'model' => $this->findModel($id),
            'sidebarProvider' => $sidebarProvider,
            'searchModelComment' => $searchModelComment,
            'dataProvider' => $dataProvider,
            'modelcomment' => $modelcomment,
        ]);
        }

    }

    /**
     * Deletes an existing Review model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Review model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Review the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Review::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/review/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Review */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="review-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => true])->label('Games Title') ?>

    <?= $form->field($model, 'file')->fileInput() ?>

    <?= $form->field($model, 'dsc')->widget(CKEditor::className(),[
    'editorOptions' => [
        'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
        'inline' => false, //по умолчанию false
    ],
]); ?>

    <?= $form->field($model, 'id_author')->textInput(['readonly' => true, 'value' =>  Yii::$app->user->identity->firstname." ".Yii::$app->user->identity->lastname]) ?>

    <?= $form->field($model, 'status')->dropDownList([ 'Draft' => 'Draft', 'Active' => 'Active', ], ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

    <script>
        CKEDITOR.replace( 'Review[dsc]' );
    </script>

backend/views/review/_formcomment.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $modelcomment backend\modelcomments\Comment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comment-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($modelcomment, 'id_review')->textInput()
  ->hiddenInput(['value' => $idpost]) ?>

    <?= $form->field($modelcomment, 'id_usercomment')->textInput() ?>

    <?= $form->field($modelcomment, 'commentdesc')->textarea(['rows' => 6]) ?>

    <?= $form->field($modelcomment, 'commenton')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($modelcomment->isNewRecord ? 'Create' : 'Update', ['class' => $modelcomment->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/review/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SearchReview */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="review-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idpost') ?>

    <?= $form->field($model, 'subject') ?>

    <?= $form->field($model, 'img') ?>

    <?= $form->field($model, 'dsc') ?>

    <?= $form->field($model, 'id_author') ?>

    <?php // echo $form->field($model, 'createon') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/review/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Review */

$this->title = 'Create Review';
$this->params['breadcrumbs'][] = ['label' => 'Reviews', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="review-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/review/detail.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\widgets\ActiveForm;
use yii\bootstrap\modal;


/* @var $this yii\web\View */
/* @var $model app\models\Review */

$this->title = $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Reviews', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<!--<div class="review-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->idpost], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->idpost], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idpost',
            'subject',
            'img',
            'dsc',
            'id_author',
            'createon',
            'status',
        ],
    ]) ?>
--><br/>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">

            <?php  
                
                    echo "<div class='row'>
                    <div class='col-lg-4 col-sm-12'><a href='index.php?r=review%2Fdetail&id={$model->idpost}' class='portfolio-box'>";
                    if($model->img==''){
                        echo "<img src='../../img/noimages.jpg' class='img-responsive' alt='' style='width:100%'>";
                    }
                    else{
                        echo "<img src='../../{$model->img}' class='img-responsive' alt='' style='width:100%'>";                        
                    }
                    echo "<div class='portfolio-box-caption'>
                                    <div class='portfolio-box-caption-content'>
                                        <div class='project-category text-faded'>
                                            {$model->idCategory->categoryname}
                                        </div>
                                        <div class='project-name'>
                                            {$model->subject}
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <div class='row'>
                                <hr>
                                <div class='col-lg-6 col-sm-6 text-center'>
                                    <p style='font-family:arial;font-size:12px'><i class='glyphicon glyphicon-time'></i> {$model->createon}</p>
                                </div>
                                <div class='col-lg-6 col-sm-6 text-center'>
                                    <p style='font-family:arial;font-size:12px'><i class='glyphicon glyphicon-user'></i> {$model->idAuthor->firstname} {$model->idAuthor->lastname}</p>
                                </div>
                            </div>
                            <div class='row' style='margin-top:100px'>
                                <div class='col-lg-12 col-sm-4'>
                                    <h2>You May Also Like</h2>
                                </div>"; ?>


                                <?php  
                                    foreach ($sidebarProvider->models as $sidebarProvider) {     
                                        echo "<div class='col-lg-12 col-sm-12'><a href='details?id={$sidebarProvider->idpost}' class='portfolio-box'>";
                                        if($sidebarProvider->img==''){
                                            echo "<img src='../../img/noimages.jpg' class='img-responsive' alt='' style='width:100%;max-height:200px'>";
                                        }
                                        else{
                                            echo "<img src='../../{$sidebarProvider->img}' class='img-responsive' alt='' style='width:100%;max-height:200px'>";
                                        }
                                        echo "<div class='portfolio-box-caption'>
                                                        <div class='portfolio-box-caption-content'>
                                                            <div class='project-category text-faded'>
                                                                {$sidebarProvider->idCategory->categoryname}
                                                            </div>
                                                            <div class='project-name'>
                                                                {$sidebarProvider->subject}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </a>
                                            </div><br/>";
                                    } 
                                ?>

                                <?php echo "
                            </div>
                    </div>
                    <div class='col-md-8'>";?>

                                    <?php if(isset($done)){echo "<div class='alert alert-success alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong> Thankyou !</strong> You Comment has been update to this review.</div>";}else{} ?>
                        <?php 
                        if(isset(Yii::$app->user->identity->id)){
                            if($model->id_author==Yii::$app->user->identity->id){ 

                            echo "<p style='float:left' class='btn btn-success'>{$model->status}</p>
                                <p style='text-align:right'>"; ?>

                                <?= Html::a('Update', ['update', 'id' => $model->idpost], ['class' => 'btn btn-info']) ?>
                                <?= Html::a('Delete', ['delete', 'id' => $model->idpost], [
                                    'class' => 'btn btn-danger',
                                    'data' => [
                                        'confirm' => 'Are you sure you want to delete this item?',
                                        'method' => 'post',
                                    ],
                                ]) ?>
                             <?php }else{}}else{} ?>

                    <?php echo "</p>
                        <h1 class=' text-center'>{$model->subject}</h1>
                        <hr class='colored'>
                        <div style='font-size:14px'>{$model->dsc}</div>";
                            
            ?>

            

                        <?php 

                        if(isset(Yii::$app->user->identity->id)){
                            if($model->id_author==Yii::$app->user->identity->id){ 

                            echo "<p style='float:left' class='btn btn-success'>{$model->status}</p>
                                <p style='text-align:right'>"; ?>

                                <?= Html::a('Update', ['update', 'id' => $model->idpost], ['class' => 'btn btn-info']) ?>
                                <?= Html::a('Delete', ['delete', 'id' => $model->idpost], [
                                    'class' => 'btn btn-danger',
                                    'data' => [
                                        'confirm' => 'Are you sure you want to delete this item?',
                                        'method' => 'post',
                                    ],
                                ]) ?>
                             <?php }else{}}else{} ?>
                                <div class='col-lg-12 col-sm-12' style='border-top:1px #F0F0F0 solid;padding:20px 0'>


                                    <!--<p>
                                        <?= Html::a('Create Comment', ['/comment/create'], ['class' => 'btn btn-success']) ?>
                                    </p>-->

                                    
                                <?php 
                                    if(isset(Yii::$app->user->identity->id)){ ?>
                                    <div class="comment-form">

                                        <?php $form = ActiveForm::begin(['id'=>$model->formName()]); $idpost = "{$model->idpost}";?>
                                        
                                        <?= $form->field($modelcomment, 'id_review')->textInput()
                                                  ->hiddenInput(['value' =>  $idpost])
                                                  ->label(false); ?>
                                                        
                                        <?= $form->field($modelcomment, 'id_usercomment')->textInput() 
                                                  ->hiddenInput(['value' => Yii::$app->user->identity->id])
                                                  ->label(false); ?>

                                        <?= $form->field($modelcomment, 'commentdesc')->textarea(['rows' => 6])
                                                  ->label(false); ?>

                                        <?= $form->field($modelcomment, 'commenton')->textInput() 
                                                  ->hiddenInput(['value' => date('Y-m-d h:m:s')])
                                                  ->label(false); ?>

                                        <div class="form-group">
                                            <?= Html::submitButton($modelcomment->isNewRecord ? 'Add Comment' : 'Update', ['class' => $modelcomment->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                                        </div>

                                        <?php ActiveForm::end(); ?>

                                    </div>
                                    <?php }else{
                                        echo "<a href='".Yii::$app->urlManagerFrontEnd->createUrl('/site/login')."' class='btn btn-success'>Login to Add Comment</a>";
                                    } ?>
                                </div><div class='col-lg-12 col-sm-12' style='border-top:1px #F0F0F0 solid;padding:20px 0 50px 0'>

                                    <?= ListView::widget([
                                        'dataProvider' => $dataProvider,
                                        'itemView' => function($searchModelComment)
                                        {
                                            return "<div class='row well' style='border-bottom: 1px solid #f0f0f0;'><div class='col-lg-8 col-sm-6'><b>".$searchModelComment->idUsercomment->firstname." ".$searchModelComment->idUsercomment->lastname."</b></div><div class='col-lg-4 col-sm-6 text-right'><span style='font-size:10px'>".$searchModelComment->commenton."</span></div><div class='col-lg-12 col-sm-12' style='line-height:2;'>".$searchModelComment->commentdesc."</div></div>";
                                        }
                                        /*
                                        'filterModel' => $searchModelComment,
                                        'columns' => [
                                            ['class' => 'yii\grid\SerialColumn'],

                                            'idcomment',
                                            'id_review',
                                            'id_usercomment',
                                            'commentdesc:ntext',
                                            'commenton',

                                            ['class' => 'yii\grid\ActionColumn'],
                                        ],*/
                                    ]); ?>

                        </div>
                    </div>
            </div>
        </div>




    </section>

</div>

backend/views/review/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SearchReview */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Reviews';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="review-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Review', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'idpost',
            'subject',
            'img',
            'dsc',
            'id_author',
            // 'createon',
            // 'status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/review/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Review */

$this->title = $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Reviews', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->idpost, 'url' => ['view', 'id' => $model->idpost]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="review-update">

    <?= Html::a('Cancel', ['details', 'id' => $model->idpost], [
        'class' => 'btn btn-danger pull-right',
        'data' => [
            'confirm' => 'Are you sure to cancel update this review ?',
        ],
    ]) ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/review/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Review */

$this->title = $model->idpost;
$this->params['breadcrumbs'][] = ['label' => 'Reviews', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="review-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->idpost], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->idpost], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idpost',
            'subject',
            'img',
            'dsc',
            'id_author',
            'createon',
            'status',
        ],
    ]) ?>

</div>